added codesystem for messages of rezeptanforderung
gematik/api-app-transport-framework pull request #6
Opened 2023-03-03 11:16 UTC by SvenSommer

2023-03-03 11:59 UTC, HendrikGematik approved these changes

2023-03-06 05:55 UTC, florianschoffke requested changes

2023-03-06 05:55 UTC, florianschoffke commented on src/fhir/input/fsh/codesystems/GEM-CS-KIM-Dienstkennung.fsh
> +* #eRezept_ParenteraleErnaehrung_Rezeptbestaetigung "Bestätigung und übermittlung eines ausgestellten Rezeptes für eine parenterale Zubereitung"
Übermittlung groß schreiben

2023-03-06 05:55 UTC, florianschoffke commented on src/fhir/input/fsh/codesystems/GEM-CS-KIM-Dienstkennung.fsh
> +* #eRezept_Rezeptanforderung_Rezeptbestaetigung "Bestätigung und übermittlung eines ausgestellten Rezeptes"
Übermittlung groß schreiben

2023-03-06 07:46 UTC, merged